<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:tns="http://localhost:8000/soap/client"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             name="ClientService"
             targetNamespace="http://localhost:8000/soap/client">

  <types>
    <xsd:schema targetNamespace="http://localhost:8000/soap/client">
      <xsd:element name="register">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="document" type="xsd:string"/>
            <xsd:element name="name" type="xsd:string"/>
            <xsd:element name="email" type="xsd:string"/>
            <xsd:element name="phone" type="xsd:string"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="registerResponse">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="success" type="xsd:boolean"/>
            <xsd:element name="cod_error" type="xsd:string"/>
            <xsd:element name="message" type="xsd:string"/>
            <xsd:element name="data" type="xsd:anyType" minOccurs="0"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:schema>
  </types>

  <message name="registerRequestMessage">
    <part name="parameters" element="tns:register"/>
  </message>
  
  <message name="registerResponseMessage">
    <part name="parameters" element="tns:register"/>
  </message>

  <portType name="ClientServicePortType">
    <operation name="register">
      <input message="tns:registerRequestMessage"/>
      <output message="tns:registerResponseMessage"/>
    </operation>
  </portType>

  <binding name="ClientServiceBinding" type="tns:ClientServicePortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="register">
      <soap:operation soapAction="http://localhost:8000/soap/client"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>

  <service name="ClientService">
    <port name="ClientServicePort" binding="tns:ClientServiceBinding">
      <soap:address location="http://localhost:8000/soap/client"/>
    </port>
  </service>
</definitions>
